sudo: required
language: scala

dist: trusty

scala:
  - 2.12.14
  - 2.13.4

jdk:
  - openjdk11

services:
  - mysql

addons:
  postgresql: "13"


cache:
  directories:
    - $HOME/.m2
    - $HOME/.ivy2
    - $HOME/.sbt

before_script:
  - ./script/prepare_build.sh

notifications:
  email:
    - jilen.zhang@gmail.com
