language: scala

dist: trusty

jdk:
  - openjdk8
  - openjdk11

services:
  - postgresql
  - mysql
cache:
  directories:
    - vendor/bundle
    - $HOME/.m2
    - $HOME/.ivy2
    - $HOME/.sbt
before_script:
  - ./script/prepare_build.sh

notifications:
  email:
    - jilen.zhang@gmail.com
