language: scala

dist: xenial

jdk:
  - openjdk8
  - openjdk11

services:
  - mysql

addons:
  postgresql: "9.4"


cache:
  directories:
    - $HOME/.m2
    - $HOME/.ivy2
    - $HOME/.sbt

before_script:
  - ./script/prepare_build.sh

notifications:
  email:
    - jilen.zhang@gmail.com
